{
 "title": "Betting companies profits",
 "time": { "from": "2020-10-09T04:58:30.000Z", "to": "2020-10-09T05:16:30.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# **Betting Websites**\n--------------------------------\n## * *Bet 365*  -> [B365](https://www.nj.bet365.com)\n## * *Bwin*  -> [BW](https://sports.bwin.com/en/sports)\n## * *Interwetten*  -> [IW](https://www.interwetten.com/en/sportsbook)\n## * *Pinnacle*  -> [PS](https://www.pinnacle.com/en/)      \n## * *William hill* -> [WH](https://www.williamhill.com/)\n## * *Bet Victor*  -> [VC](https://www.betvictor.com/)\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Betting Websites Profits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  \"bet_company\" AS metric,\n  sum(winnings) AS \"winnings\"\nFROM clickstream\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Average profit - ODD type",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  \"bet_type\" AS metric,\n  avg(winnings) AS \"winnings\"\nFROM clickstream\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1,2\nORDER BY 1,2\n\n"
    }
   ]
  },
  {
   "title": "Profits over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  \"bet_company\" AS metric,\n  avg(winnings) AS \"profits\"\nFROM clickstream\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  }
 ]
}